name: CI/CD for HTML Page

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # No install dependencies step needed for static HTML

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: html-files
          path: |
            index.html
            style.css
            game.js

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: html-files
          path: ./website

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.KEY1 }}
          publish_dir: ./website
